// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXWWHmzT8x7nN4_9cJXoicq31Kt4AqeLY',
    appId: '1:894207849285:web:ebb95acbf1df54f70b042c',
    messagingSenderId: '894207849285',
    projectId: 'leaflet-b8384',
    authDomain: 'leaflet-b8384.firebaseapp.com',
    storageBucket: 'leaflet-b8384.firebasestorage.app',
    measurementId: 'G-NTKTLEQ43E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAblu_CgBI0CbrElPS1SHbs340u9P8CexY',
    appId: '1:894207849285:android:43d4390f4e96d39a0b042c',
    messagingSenderId: '894207849285',
    projectId: 'leaflet-b8384',
    storageBucket: 'leaflet-b8384.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA809eUfqXoLxhsZxaj3eLPqEUl9wu0FJk',
    appId: '1:894207849285:ios:af7068b374f9db6f0b042c',
    messagingSenderId: '894207849285',
    projectId: 'leaflet-b8384',
    storageBucket: 'leaflet-b8384.firebasestorage.app',
    iosBundleId: 'com.example.leafletApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA809eUfqXoLxhsZxaj3eLPqEUl9wu0FJk',
    appId: '1:894207849285:ios:af7068b374f9db6f0b042c',
    messagingSenderId: '894207849285',
    projectId: 'leaflet-b8384',
    storageBucket: 'leaflet-b8384.firebasestorage.app',
    iosBundleId: 'com.example.leafletApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXWWHmzT8x7nN4_9cJXoicq31Kt4AqeLY',
    appId: '1:894207849285:web:9697d80c956482bc0b042c',
    messagingSenderId: '894207849285',
    projectId: 'leaflet-b8384',
    authDomain: 'leaflet-b8384.firebaseapp.com',
    storageBucket: 'leaflet-b8384.firebasestorage.app',
    measurementId: 'G-N1ZSPJ16V1',
  );
}
